before_script:
- git submodule init
- git submodule update

variables:
  USE_GHCJS: "--compiler ghcjs-0.2.0.20151029_ghc-7.10.2"

pages:
  stage: deploy
  script:
  - "stack --no-terminal build $USE_GHCJS"
  - "minifyjs $(stack path $USE_GHCJS --local-install-root)/bin/pekabeaver.jsexe/all.js pekabeaver.min.js"
  - "mkdir assetpack"
  - "stack --no-terminal build"
  - "mkdir public"
  - "mv index.html pack.bin assetpack public/"
  tags:
  - haskellstack
  - ghcjs
  artifacts:
    paths:
    - public
  only:
  - master
