resolver: lts-5.5

packages:
- '.'
- location:
    git: https://github.com/quyse/flaw.git
    commit: c6080c30bea7adaa768f1e0f6b5061847d13551e
  subdirs:
  - flaw-app
  - flaw-asset
  - flaw-asset-dxt
  - flaw-base
  - flaw-build
  - flaw-canvas
  - flaw-collada
  - flaw-dx11
  - flaw-ffi
  - flaw-font
  - flaw-game
  - flaw-gl
  - flaw-glsl
  - flaw-graphics
  - flaw-input
  - flaw-math
  - flaw-sdl
  - flaw-sl
  - flaw-visual
  - flaw-window
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.1

ghc-options:
  "*": -O3 -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -fno-warn-tabs

rebuild-ghc-options: true
