resolver: lts-5.9

packages:
- '.'
- location:
    git: https://github.com/quyse/flaw.git
    commit: 351226df5957229d981f53c8c9cf7f1666b6c3da
  subdirs:
  - flaw-app
  - flaw-asset
  - flaw-asset-dxt
  - flaw-base
  - flaw-build
  - flaw-canvas
  - flaw-collada
  - flaw-dx11
  - flaw-ffi
  - flaw-font
  - flaw-game
  - flaw-gl
  - flaw-graphics
  - flaw-input
  - flaw-js
  - flaw-math
  - flaw-sdl
  - flaw-sl
  - flaw-visual
  - flaw-window
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.1

ghc-options:
  "*": -O3 -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -fno-warn-tabs

rebuild-ghc-options: true
