resolver: lts-5.5

packages:
- '.'
- location:
    git: https://github.com/quyse/flaw.git
    commit: e58e489fea82f0ffa41402eb9c97428dae36ad41
  subdirs:
  - flaw-app
  - flaw-asset
  - flaw-asset-dxt
  - flaw-base
  - flaw-build
  - flaw-canvas
  - flaw-collada
  - flaw-dx11
  - flaw-ffi
  - flaw-font
  - flaw-game
  - flaw-gl
  - flaw-glsl
  - flaw-graphics
  - flaw-input
  - flaw-math
  - flaw-sdl
  - flaw-sl
  - flaw-visual
  - flaw-window
  extra-dep: true
- location:
    git: https://github.com/ghcjs/ghcjs-base
    commit: 23b1311a98c7981c7b98ac7d37a6fa9456c893d5
  extra-dep: true
- location:
    git: https://github.com/ghcjs/ghcjs-dom
    commit: bbd0e70f7dae6d8d9b89b7307f2d0acf613836a7
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.1

ghc-options:
  "*": -O3 -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -fno-warn-tabs

rebuild-ghc-options: true
